added-masonry-layout-file
murtazshaikh/15_Masonry_Layout pull request #1
Opened 2022-02-03 15:14 UTC by murtazshaikh

review pr...

2022-02-11 19:41 UTC, OSAMA478 approved these changes
Nice...

2022-02-12 12:35 UTC, anask601 approved these changes

2022-02-12 15:37 UTC, syedabdullahali approved these changes

2022-02-13 17:21 UTC, Abbas4tech requested changes

2022-02-13 17:21 UTC, Abbas4tech commented on style.css
> +    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
What does this `auto-fill` affect ??? @murtazshaikh

2022-02-13 17:21 UTC, Abbas4tech commented on style.css
> +    grid-auto-flow: dense;
Can you explain what will it affect @murtazshaikh

2022-02-13 17:21 UTC, Abbas4tech commented on style.css
> +    grid-row: span 1;
What is the meaning of writing `span` here @murtazshaikh

2022-02-26 18:37 UTC, murtazshaikh commented
> Nice...

Thankyou @OSAMA478

2022-04-26 12:10 UTC, merged